services:
  - type: web
    name: zaiproxy
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: DEFAULT_KEY
        generateValue: true
      - key: DASHBOARD_ENABLED
        value: "true"
      - key: DEFAULT_STREAM
        value: "true"
      - key: DEBUG_MODE
        value: "false"
      - key: DEFAULT_LANGUAGE
        value: "en-US"
      - key: ZAI_TOKEN
        sync: false
